apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-e0hc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xfzo-tenant/rhtap-demo-app/hacbs-test-project-e0hc@sha256:a2f866ff38d1f4dd37db381e3be3119415a11dee18a6137be3d839dccd921311
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
