apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-e0hc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-e0hc
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-e0hc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-e0hc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-e0hc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xfzo-tenant/rhtap-demo-app/hacbs-test-project-e0hc@sha256:a2f866ff38d1f4dd37db381e3be3119415a11dee18a6137be3d839dccd921311
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
